# Generated by Django 3.2 on 2021-04-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IamCodeAddicted_Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviespurchase',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='IamCodeAddicted_Base.movie'),
        ),
    ]
