# Generated by Django 3.2 on 2021-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IamCodeAddicted_Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.DateTimeField(),
        ),
    ]
