# Generated by Django 3.2 on 2021-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IamCodeAddicted_Base', '0002_alter_moviespurchase_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.FloatField(default=19.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
