# Generated by Django 3.2 on 2021-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IamCodeAddicted_Base', '0003_auto_20210419_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
