# Generated by Django 3.2 on 2021-04-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IamCodeAddicted_Base', '0003_auto_20210416_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviespurchase',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='IamCodeAddicted_Base.movie'),
        ),
        migrations.AlterField(
            model_name='moviespurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
