# Generated by Django 3.2 on 2021-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IamCodeAddicted_Base', '0005_auto_20210419_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
